language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"
# uncomment this line if your project needs to run something other than `rake`:

before_script:
  - wget https://cdn.crate.io/downloads/releases/crate-0.47.3.tar.gz -O /tmp/crate.tar.gz
  - tar -xvf /tmp/crate.tar.gz
  - bundle exec ruby spec/test_server.rb $PWD/crate-0.47.3/ true

script: bundle exec rspec spec

