name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:

      # Run all jobs to completion (false), or cancel
      # all jobs once the first one fails (true).
      fail-fast: false

      matrix:
        os: [ "ubuntu-latest" ]
        ruby-version: [ "2.7" ]

    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 44200:4200

    name: Ruby ${{ matrix.ruby-version }} on OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          architecture: x64

      - name: Caching of Ruby gems
        uses: actions/cache@v3
        id: cache-gems
        with:
          path: vendor/bundle
          key: gems-os=${{ matrix.os }}-ruby=${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        run: |
          # Remove version constraint once upgrading ruby itself
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install

      - name: Run tests
        run: bundle exec rspec
